### ISSUE TITLE
How to understand Opentracing ?

### ISSUE THREAD

**Issue by tomgithub2016** [opentracing/opentracing-java#100]
Hi, 
    In my project,there are two services. 

    ServiceA is Client ( CS、CR)  and  ServiceB(SS、SR)  is Server,

    A send a request to B, B response to A. one request and response.

My question is ,In this scenario， 
  
        （1） If use opentracing  on ServiceA and ServiceB，How many span to build on ServiceA and ServiceB ? only one or two?

        （2） CS、CR、SS、SR ，their spanId  should be the same?

**Comment by yurishkuro** [comment]
If you use OpenTracing, it's always two spans. Whether they have unique span IDs or share the same (as Zipkin does) is the implementation detail of the tracer.

**Comment by tomgithub2016** [comment]
@yurishkuro  ,
Ok I  understand; 
```
Service A will build span1  and  inject to request header send to the ServiceB.
ServiceB will extract request header ,and build span2

```My question is:
 span2 must be the asChildOf span1?   I do not think so.

**Comment by yurishkuro** [comment]
yes, you would start span2 with

```
spanCtx = tracer.extract(...)
span2 := tracer.start_span("endpoint name", child_of=spanCtx)
```

If you don't do that, span2 will have a completely different trace ID.

**Comment by bhs** [comment]
(closing since this isn't really an OT-Java issue... @tomgithub2016 please reopen against the opentracing/specification repo if you think additional clarification is needed)
