### ISSUE TITLE
Shouldn't Span implement AutoCloseable not Closeable?

### ISSUE THREAD

**Issue by mniebla** [opentracing/opentracing-java#102]
AFAIK the `Closeable` interface was intended for releasing resources *related to* IO operations...which is why it throws IOException. 

Whereas the `AutoCloseable` interface...was intended for releasing *general* resources.

This means when we want to...

```java
try(Span span = getSpan()){
    // do stuff
}
```

We have to handle an IOException....which seems odd...since we are only closing a Span.

Since your POM defines version `<main.java.version>1.7</main.java.version>`, I'm guessing you didnt use `Closeable` to maintain backwards compat with Java 6

**Comment by sjoerdtalsma** [comment]
AFAIK `opentracing-api` actually is `1.6` ?

**Comment by wu-sheng** [comment]
I think it should be.

https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/pom.xml#L32

**Comment by bhs** [comment]
@mniebla the only reason for this is 1.5 compatibility, but that's a requirement for many OT users. I'm going to close this, but please reopen if you think that's an inadequate explanation.

PS: sorry to miss this the first time around!
