### ISSUE TITLE
How to access Span id (trace id) ?

### ISSUE THREAD

**Issue by davidB** [opentracing/opentracing-java#105]
Hi,

My Use Case, I would like to have read access to the Span id (SpanContext id) to be able to use it in log and in error reported (to end user,...).

Is it possible ?
* if yes what is the way ?
* if no, why ?

Thanks.

**Comment by wu-sheng** [comment]
Right now, in OpenTracing Specification, these if no way to get the `id`s. Because, in the spec, we did not define how to generate these `id`, even whether exist these `id`s or not. It depends on the tracer implementation. 

For example, [sky-walking](https://github.com/wu-sheng/sky-walking)  tracer implementation only have traceSegmentId and Span SequenceId, but no ContextId.

**Comment by wu-sheng** [comment]
And I know your scenario, if you want to do that, you depend the specific implementation. I think most tracer implementations provide their own API to get that. 

In sky-walking, I did it by providing a toolkit, a set of new APIs. https://github.com/wu-sheng/sky-walking/wiki/sky-walking-application-toolkit-log4j-1.x

**Comment by davidB** [comment]
@wu-sheng , thanks for the info.
But I need to be expose the "trace id" in error message, then dev could use the trace to debug error reported by support, QA, end-user. 
In the case of error, I thought to use "injector" like for remote call. But I guess I could not use injector (for bad performance) for logging (with log4j, logback,...). The solution provide sky-walking is nice, but doesn't fit my need (I search something more tracer and framework agnostic).

**Comment by wu-sheng** [comment]
@davidB I agree, `injector` would not be a good choice, but the performance may be not that bad, most tracer just gave a snapshot of current context, mostly a get/set op. I concern, if using `injector` like that, the tracer may prepared for a remote call, that might influence the analysis.

> I search something more tracer and framework agnostic

I thought if this is the goal, we should discuss on OpenTracing specification level, bring this issue to `opentracing/specification`.  But even we can agree on given a certain API about this,  I am not sure the return value should be a ID, always, also depend on the tracer implementation.

e.g.
- Tracer A, `toString` returns `traceSegmentId=xxx, spanId=xxx`
- Tracer B, `toString` returns `globalSpanId=xxx`

**Comment by yurishkuro** [comment]
Please see http://stackoverflow.com/questions/42699603/how-can-i-get-a-trace-id-from-opentracing-api

**Comment by davidB** [comment]
thanks for the feeback and links.

**Comment by wu-sheng** [comment]
@davidB , I think this discussion in spec level, meets your demand. You can check on that.

https://github.com/opentracing/specification/issues/24#issuecomment-286261320
