### ISSUE TITLE
Open Tracing API and JUL Logging

### ISSUE THREAD

**Issue by tahini** [opentracing/opentracing-java#110]
I'm a developer on the Trace Compass trace analyzer/visualizer project. We started using JUL logging in our application and the data we save is such that it is very similar in semantic to the Open Tracing API (we get the same causality between spans and extra data, etc).

I'm looking at the Open Tracing API to see if we can use that instead, if it could simplify the developer's lives.

The advantages of JUL that I see over Open Tracing API are the use of class-specific Loggers (though the SpanContext can replace that maybe). But most importantly, the hability to set the LogLevel of our trace points and configure our logging needs at runtime through a simple properties file. I have the impression that Open Tracing API is a all-or-nothing tracing depending on what library implementation is loaded at runtime. Am I wrong?

Have you thought of a relationship between JUL logging and Open Tracing API? I see the Open Tracing API more like defining what fields/data should be in the message, and JUL remains the vehicle to trace. I guess we could implement a JUL Tracer and use that tracer in our code. Or the other way around: wrap our JUL statements in utility methods that would create the proper OpenTracing API objects, so that we can still take advantage of LogLevels.

Any thoughts on this?

**Comment by pavolloffay** [comment]
@tahini Hello,

this might be interesting for you https://github.com/opentracing-contrib/meta/issues/14

**Comment by tahini** [comment]
Thanks, I'll look at it. Do you know of any open source project that makes use of the Open Tracing API, as example usages?

**Comment by objectiser** [comment]
Hi @tahini, I'm currently working on an OpenTracing component for Apache Camel, which should allow any camel application to be instrumented and report tracing data to any configured OpenTracing compliant Tracer.

This will be available in the next version of Camel (2.19.0), but if you wanted to give it a try, its available in the latest snapshot.

See https://github.com/apache/camel/tree/master/examples/camel-example-opentracing for an example.

**Comment by yurishkuro** [comment]
Do you know of any open source project that makes use of the Open Tracing API, as example usages?

@tahini Uber's TChannel and YARPC projects both support OpenTracing natively.

**Comment by tedsuo** [comment]
Spring cleaning: This conversation has been moved here, which is a better spot or it since it's OT-wide and not Java-specific: https://github.com/opentracing/specification/issues/57

I'm closing this for now, feel free to reopen or create a new issue once the specification debate on log levels has been resolved.
