### ISSUE TITLE
PEER_PORT shouldn't be ShortTag

### ISSUE THREAD

**Issue by malafeev** [opentracing/opentracing-java#113]
PEER_PORT is ShortTag.
In Java Short range is from  MIN_VALUE = -32768 to MAX_VALUE = 32767
http://docs.oracle.com/javase/7/docs/api/java/lang/Short.html
How I can set port greater than 32767 ?

**Comment by wu-sheng** [comment]
Thanks for your report. I just pr the codes to fix this.

**Comment by yurishkuro** [comment]
```java
  public static void main(String[] args) {
    long port = 33000;
    short shortPort = (short) port;
    System.out.println(shortPort);
  }
```

**Comment by wu-sheng** [comment]
@yurishkuro The output is `-32536`, it do not equal the expected value.

**Comment by wu-sheng** [comment]
> -1 - this is API breaking change. A cast to short still preserves the full 16 bits of the port.

I understand your concern. But it really should add this cast operation, when you set a port....

**Comment by yurishkuro** [comment]
Well, semantically it's the correct representation, e.g. InetSocketAddress defines the port as `int`, but in the comments limits the range "value is between 0 and 65535" (i.e. unsigned short). I agree that `int` would've been more convenient in practice, but it will be an API breaking change which will break existing instrumentations.

**Comment by wu-sheng** [comment]
Agee. Maybe I can change the pr, add some comments of PEER_PORT to describe this. In cases others have the same questions. Thoughts? @yurishkuro

**Comment by yurishkuro** [comment]
Yes, definitely makes sense to clarify the comments for that tag.

If others are ok to break backwards compatibility, I can be out-voted :-) After all, Java is still <1.0

**Comment by wu-sheng** [comment]
I hesitate about breaking backwards compatibility too. I will cc the pr to other contributors, see what happen next? OK?

**Comment by wu-sheng** [comment]
Just done. https://github.com/opentracing/opentracing-java/pull/114#issuecomment-289654079

**Comment by wu-sheng** [comment]
Merged already.
