### ISSUE TITLE
Provide mechanism for unwrapping spans

### ISSUE THREAD

**Issue by jakerobb** [opentracing/opentracing-java#126]
In https://github.com/openzipkin/brave-opentracing/issues/39, I oversimplified my solution. My span was actually an AutoReleasingManagedSpan. I had to write additional code to unwrap it, as follows:

```
    public static Span unwrapSpan(Span span) {
        while (true) {
            if (span instanceof ManagedSpan) {
                ManagedSpan managedSpan = (ManagedSpan) span;
                span = managedSpan.getSpan();
                continue;
            }
            return span;
        }
    }
```

A solution could go in ot-spanmanager, but that seems like it's going to become part of ot-java soonish and more changes would probably delay that, so I'm posting it here with the expectation that a solution would wait until https://github.com/opentracing/opentracing-java/pull/115 is merged.

The solution wouldn't necessarily need to be a static utility method. With SpanManager baked into ot-java, Spans could just have an `unwrap` method that recursively finds the innermost wrapped span. @devinsba has something similar he wrote: https://gitter.im/openzipkin/zipkin?at=5903978bd32c6f2f094dfd75

**Comment by bhs** [comment]
@jakerobb what's the status on this post-115?

**Comment by jakerobb** [comment]
I think that's a better question for @devinsba.

**Comment by tedsuo** [comment]
Spring cleaning here: I believe this is fine - or at least differently wrong - now that we have active span manager. @jakerobb do you mind if closing this issue for now and reopen/make-a-new-one later?

**Comment by jakerobb** [comment]
Forgive me for not being up to speed on the latest developments -- I didn't notice that #115 had been merged. I poked around a bit and found ActiveSpanSource -- is that what you're referring to? Skimming the documentation, it seems like we simply don't wrap spans anymore, obviating the need for this issue. 

If that's the case, please confirm and I'll be happy to close. Thanks!

**Comment by tedsuo** [comment]
Yep, that's correct! The API has changed significantly (we should do a blog post about it), but there should be no need to wrap spans, store the active span in a  thread local, etc, with the new API.

**Comment by jakerobb** [comment]
Great! Thanks. A blog post with advice for people converting from earlier versions would be very helpful.
