### ISSUE TITLE
Move TracerResolver to core java repo util module

### ISSUE THREAD

**Issue by objectiser** [opentracing/opentracing-java#130]
As recently happened with the GlobalTracer, I think it would be useful to have the [TracerResolver](https://github.com/opentracing-contrib/java-tracerresolver) functionality moved from the contrib repo into the core java repo, as it is something users are expecting to be part of the core API.

Realise we may want to work on the functionality in the contrib repo for a while longer, so this issue is a placeholder to register the issue, and collect opinions for and against the move.

**Comment by bhs** [comment]
I can def see the rationale for this one. The counterargument would mainly be that it's not strictly necessary... but as the agent-based approach gains momentum it makes more and more sense.

I would like to see things bake a little more in contrib if that's not making life difficult for anyone, though.

**Comment by objectiser** [comment]
Agree it needs more bake time in contrib, but it isn't just the agent that benefits from this capability - https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/microprofile/YxKba36lye4/KalHGB-gAgAJ

It enables applications to switch between tracer implementations without any code changes.

**Comment by bhs** [comment]
@objectiser yes, understood that it allows zero-code-modification Tracer swaps... my point is merely that a particular process can choose to enable this capability regardless of whether the functionality lives in the core OT-Java artifact. Compare against GlobalTracer where instrumented code sitting low in the stack *must* use the same Tracer instance as instrumented code sitting higher in the stack... in that case, it's important for OT-Java to have an opinion about what GlobalTracer is "official".

(Sorry for the lengthy delay, this dropped off my inbox along with a variety of other things)

**Comment by tedsuo** [comment]
Spring cleaning here: sounds like this is resolved for now. @objectiser can we close this for now and reopen it later when someone wants to move on it? Possibly we can create a github label for "not-now-but-good-idea" so that these issues are easier to dig up in the future.

**Comment by objectiser** [comment]
Yes can be closed for now.
