### ISSUE TITLE
OpenTracing encourages classloader-scoped configuration

### ISSUE THREAD

**Issue by adriancole** [opentracing/opentracing-java#140]
I find it very strange that in 2017, OpenTracing are encouraging and proliferating classloader-scoped configuration as status quo. Considering all the work in the last decade in JVM configuration, it is surprising that new instrumentation are being made that rely *first* on the expanding new set of apis like `DefaultSpanManager.getInstance()`. There are numerous better ways to accomplish the task. For example, why would you configure your service with CDI, Guice, Spring, OSGi, Dagger, yet have it poke around for classloader statics?

The only reasons I can think of for this optimization are:
* people who don't want to be bothered with integrating with various configuration methodologies, and find it more convenient to route users through static config instead.
* people here are trying to emulate existing logging frameworks, except loggers are different as they often live far below request (ex at bootstrap time), and have to include a system like static initialization.

Rather than proliferate dozens of projects that pin people to statics, I would suggest putting better advice here. There's a lot of instrumentation manufacturing going on which don't seem to gel with best practices. I suspect if people knew better, they would make static lookup as a last resort or opt-in vs *the way* to configure tracing.

**Comment by adriancole** [comment]
An example of good advice would be to mention the edge-cases which can only be accomplished via static lookups. These are usually themselves staticly bound bootstrap issues. For example, JDBC initialization sometimes has no hook except via the url for configuration. This is one of those cases.. That or things that are configured and bootstrapped via system properties. Main point is that there are a limited set of scenarios where you cannot reasonably configure your application except via static lookups.

Highlighting these cases give folks better guidance, and limits the scope of damage. Then, when opentracing people make new instrumentation projects, they could use this advice and avoid relying on statics for things easy to configure like http clients.

**Comment by bhs** [comment]
Just catching up on this.

@adriancole TL;DR I agree with you... see https://github.com/opentracing/opentracing-java/pull/148 and let me know what you think.
