### ISSUE TITLE
Identical packages in opentracing-api and opentracing-noop cause build failure with JDK 9 + jigsaw

### ISSUE THREAD

**Issue by kratz74** [opentracing/opentracing-java#145]
Maven dependency on opentracing-util required to use GlobalTracer.get() introduced transitive dependency on opentracing-noop and opentracing-api.
Unfortunately both opentracing-noop and opentracing-api contains the same package "io.opentracing" and this causes error in JDK 9 + jigsaw projects containing module-info.java.

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] module <module_name> reads package io.opentracing from both opentracing.api and opentracing.noop
[ERROR] module  reads package io.opentracing from both opentracing.noop and opentracing.api
[ERROR] module opentracing.api reads package io.opentracing from both opentracing.noop and opentracing.api
[ERROR] module opentracing.util reads package io.opentracing from both opentracing.noop and opentracing.api
[ERROR] module opentracing.noop reads package io.opentracing from both opentracing.noop and opentracing.api

It would be good to rename "io.opentracing" package in opentracing-noop to something like "io.opentracing.noop"

**Comment by kratz74** [comment]
This fixed this problem in my current dependency - 0.21.0 (release-0.21.0 tag)
[release-0.21.0.patch.zip](https://github.com/opentracing/opentracing-java/files/1004664/release-0.21.0.patch.zip)
Similar change should be applied on master too.

**Comment by bhs** [comment]
@kratz74 sorry for the delay. Can you submit a PR and @bhs me?

**Comment by pavolloffay** [comment]
Agree that `noop` should live in a separate package. I tried to compile with `jdk-9+171` and it worked (I had to bump versions of some plugins).

@kratz74 do you have steps to reproduce your build?

**Comment by kratz74** [comment]
[bugSample.zip](https://github.com/opentracing/opentracing-java/files/1038450/bugSample.zip)
Here is simple mvn project to reproduce it. It needs module-info.java

**Comment by kratz74** [comment]
Added PR against temporary fork in my workspace. I'll delete this fork when this is merged.

**Comment by pavolloffay** [comment]
@kratz74 thanks for submitting https://github.com/opentracing/opentracing-java/pull/150 I agree that noop should ideally live in a separate package. I am wondering whether there are other solutions to this. I will have a closer loot tomorrow.

**Comment by sparkoo** [comment]
Jigsaw does not allow same package name in two or more modules. So I guess only reasonable option is to rename one of the packages as #150 suggests.

Note: When two modules has same package and both exports it and other module reads them, it fails at compile time (your case).
When two modules has same package and one of them exports it and other module reads them, it fails at startup time.
Anyway not possible in current state of jigsaw.
