### ISSUE TITLE
API break from 0.22 to 0.30

### ISSUE THREAD

**Issue by objectiser** [opentracing/opentracing-java#147]
When trying out current camel-opentracing component against a tracer updated to use 0.30.0.RC3, got this:

> java.lang.NoSuchMethodError:
 io.opentracing.Span.setTag(Ljava/lang/String;Ljava/lang/String;)Lio/opentracing/Span;
at org.apache.camel.opentracing.decorators.AbstractSpanDecorator.pre(AbstractSpanDecorator.java:72) ~[camel-opentracing-2.20.0-SNAPSHOT.jar:2.20.0-SNAPSHOT]

The new split between Span and ActiveSpan, seems a cleaner design, so not suggesting we should revert the change - just making a note that this causes issues between these two versions.

**Comment by bhs** [comment]
@objectiser ACK, yes. What are the criteria for closing this issue?

**Comment by martinjmares** [comment]
Hi,
OK. I can accept incompatible differences between 0.22 and 0.30 but I also need some version or promise which I can include into my Java libraries without a risk of incompatible dependencies for users of my library. Something like 1.0 release with compatibility promise for all future versions. Do you plan something like that? If yes, when? If not, what is your expectation - how to use it in libraries?
BTW: Thank you for your library. I like it.

**Comment by pavolloffay** [comment]
Hi @martinjmares, yes are we planning 1.0 soon, however we don't know the exact date. Here https://github.com/opentracing/opentracing-java/milestone/ are missing issues to be resolved.

**Comment by objectiser** [comment]
@bhs issue can be closed. Was mainly to highlight the incompability.

**Comment by bhs** [comment]
@objectiser makes sense, will close.

@martinjmares I'd echo what @pavolloffay said. The additional API work for 1.0 is small... my main source of concern/delay is just seeing the ActiveSpan stuff "in the wild" for longer.
