### ISSUE TITLE
Package name for OT API

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-java#15]
Currently it's `opentracing`, which is somewhat unconventional for Java. Should it be `io.opentracing`?

@michaelsembwever @bensigelman

**Comment by michaelsembwever** [comment]
+1

**Comment by bensigelman** [comment]
Definitely!

On Wednesday, March 16, 2016, mck <notifications@github.com> wrote:

> +1
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/opentracing/opentracing-java/issues/15#issuecomment-197657988>
>


-- 
(Sent via mobile)

**Comment by oibe** [comment]
https://github.com/opentracing/opentracing-java/pull/16

**Comment by bensigelman** [comment]
thank you, @oibe!

On Thursday, March 17, 2016, oibe <notifications@github.com> wrote:

> #16 <https://github.com/opentracing/opentracing-java/pull/16>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/opentracing/opentracing-java/issues/15#issuecomment-198035105>
>


-- 
(Sent via mobile)
