### ISSUE TITLE
Why finished span still active?

### ISSUE THREAD

**Issue by malafeev** [opentracing/opentracing-java#151]
I create span, activate it and  finish.
But after that tracer shows me that there is active span.
Is it correct?

```
    MockTracer mockTracer = new MockTracer(new ThreadLocalActiveSpanSource(),
        MockTracer.Propagator.TEXT_MAP);
    Span span = mockTracer.buildSpan("test").startManual();
    mockTracer.makeActive(span);
    span.finish(); // I finish it !!!

    ActiveSpan activeSpan = mockTracer.activeSpan();
    System.out.println(activeSpan == null); // It prints false
```

**Comment by pavolloffay** [comment]
This is correct, finish does not imply deactivation :/.

**Comment by malafeev** [comment]
:( 
I need somehow deactivate span on finish (From another thread)

**Comment by pavolloffay** [comment]
This is the thing I was complaining about, but anyways you should use `.startActive` and then call `.deactivate`

**Comment by malafeev** [comment]
I cannot in the case where I don't have control over threads.
Ideally I finish span in one thread and it is deactivated it in all other threads where it was active.

My example:
I start active span in main thread. It creates callback which will be executed in thread pool.
When I should deactivate span?
If I deactivate span after callback created in main thread then inside callback span will be already finished so time tracking will be wrong.
And worse: I don't know when callback will be executed, there is no starting point. I have only `onFinish()` method.

**Comment by malafeev** [comment]
Solution which I hope work:
[main] start active span
[main] In the constructor of callback I create Continuation: `continuation = activeSpan.capture();`
It increments counter `refCount`
[main] deactivate span
[thread-pool-1] in callback `onFinish` method: `continuation.activate().deactivate();`

**Comment by bhs** [comment]
@malafeev I think that's exactly the right approach ^^^

**Comment by malafeev** [comment]
thanks @bhs
