### ISSUE TITLE
Confirm successful "prod" usage of the new active span API

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-java#154]
This is a cover issue to keep track of various efforts to incorporate the new ActiveSpan API into existing instrumentations.

  * [x] Jaeger client [upgrade to 0.30](https://github.com/uber/jaeger-client-java/issues/179) and Jaeger instrumentation upgrade [to use active span](https://github.com/uber/jaeger-client-java/issues/182)
  * [x] [Brave upgrade to 0.30](https://github.com/openzipkin/brave-opentracing/pull/43)

**Comment by sjoerdtalsma** [comment]
- [ ] [zipkin-opentracing upgrade to 0.30](https://github.com/lucidsoftware/zipkin-opentracing/pull/1)

**Comment by bhs** [comment]
- [ ] [LightStep upgrade to 0.30 (RC)](https://github.com/lightstep/lightstep-tracer-java/pull/94) has been in production for several name-brand organizations.

**Comment by adriancole** [comment]
I'm not sure how many others there are, but should be possible to find out w/ a github search. I know  @pauldraper did a lot of work on propagation in the past, so maybe add his https://github.com/lucidsoftware/zipkin-opentracing to the list?

**Comment by adriancole** [comment]
also, would other vendors like instana classify as production here? cc @CodingFabian

**Comment by sjoerdtalsma** [comment]
@adriancole My comment two above yours mentions the PR to upgrade the repo you talk about 😉 .
CC: @pauldraper (any info on that PR?)

**Comment by CodingFabian** [comment]
Just released 0.30 support for Instana Opentracing and Interop.
https://github.com/instana/instana-java-opentracing

So we might classify, but until now there was no customer using it, there was also no request from a customer for that upgrade. they are all happy with 0.20.7 which was the previous one we supported.

**Comment by pavolloffay** [comment]
Closing, all linked tracers support `0.30.0`

**Comment by wu-sheng** [comment]
Skywalking upgraded its opentracing-bridge to 0.30.0 since 3.2.x .

**Comment by sjoerdtalsma** [comment]
> Closing, all linked tracers support `0.30.0`

[zipkin-opentracing upgrade to 0.30](https://github.com/lucidsoftware/zipkin-opentracing/pull/1) hasn't been merged yet, not so sure it is still actively maintained..

**Comment by carlosalberto** [comment]
Shall we close this one as the 0.30 as been 'abandoned'? (Maybe also creating a issue tracking what Tracer systems support 0.31?) @yurishkuro

**Comment by yurishkuro** [comment]
we're running 0.31 in prod already, so yeah...
