### ISSUE TITLE
Possible race condition in GlobalTracer

### ISSUE THREAD

**Issue by netudima** [opentracing/opentracing-java#156]
https://github.com/opentracing/opentracing-java/blob/master/opentracing-util/src/main/java/io/opentracing/util/GlobalTracer.java#L68 - race condition is possible. Tracer field is mutable and can be read by different threads without synchronized section (like here: https://github.com/opentracing/opentracing-java/blob/master/opentracing-util/src/main/java/io/opentracing/util/GlobalTracer.java#L147)

Possible way to fix is to add volatile for this field

**Comment by netudima** [comment]
The same as - https://github.com/opentracing/opentracing-java/issues/157

**Comment by pavolloffay** [comment]
closed via https://github.com/opentracing/opentracing-java/pull/158
