### ISSUE TITLE
GlobalTracer::tracer should be volatile

### ISSUE THREAD

**Issue by raphw** [opentracing/opentracing-java#157]
As the [GlobalTracer::tracer](https://github.com/opentracing/opentracing-java/blob/master/opentracing-util/src/main/java/io/opentracing/util/GlobalTracer.java#L68) is only set in a synchronized block but might be dereferenced outside of it, the field must be volatile.

**Comment by wu-sheng** [comment]
Although these is little chance about initializing `GlobalTracer` in multi-thread, IMO it should initialize in starting stage, still this is a risk. I have send #158 for this.

**Comment by wu-sheng** [comment]
Has already added. Thanks
