### ISSUE TITLE
Tags.PEER_HOST_IPV4 is IntTag but spec says it should be String

### ISSUE THREAD

**Issue by szetheli** [opentracing/opentracing-java#162]
Current version of spec calls for peer.ipv4 to be type string, but the java impl Tags has it as IntTag.  This leads to confusing output for the IP address in the impls.

peer.ipv4=2130706433 (as integer)

peer.ipv4=127.0.0.1 (as spec calls for)

Should the Tags class change to match the spec or the spec change and call out that implementations should special case this if they want readability?

**Comment by wu-sheng** [comment]
@opentracing/otsc I think we have discussed similar scenario in `peer.port`, the result is we change the PEER_PORT from **ShortTag** to **IntTag**. IMO, we should change **ipv4** to **StringTag** too.

**Comment by yurishkuro** [comment]
it's a breaking change. Not worth it, imo. Maybe for 1.0

**Comment by wu-sheng** [comment]
Sorry for missing this info. Intend to change for 1.0

**Comment by yurishkuro** [comment]
@szetheli you can use `peer.address` tag, it accepts strings.

**Comment by wu-sheng** [comment]
@szetheli Now ipv4 can accept integer and string both.
