### ISSUE TITLE
GlobalTracer breaks tests because it can be initialized only once

### ISSUE THREAD

**Issue by mabn** [opentracing/opentracing-java#170]
`GlobalTracer.register` throws an exception when called again with another tracer instance. It makes unit tests fail if they happen to initialize GlobalTracer.

Has anyone run into this problem? I could run tests in separate JVM instances, but I'd rather not. Maybe adding a "reset" method would make it easier to use for testing purposes?

**Comment by malafeev** [comment]
I solve this problem only with `maven-surefire-plugin`:
```
 <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.20</version>
    <configuration>
       <reuseForks>false</reuseForks>
       <forkCount>1</forkCount
    </configuration>
</plugin>
```

**Comment by tylerbenson** [comment]
I solve this problem by using reflection to set the tracer field in `GlobalTracer` back to a `NoopTracer`.  This would probably be considered a hack, but is more efficient than starting a new JVM for every test.

**Comment by pavolloffay** [comment]
Reflection is also used in this repo 
https://github.com/opentracing/opentracing-java/blob/578d4e74d9b16c18268717e537000a88d7e6779c/opentracing-util/src/test/java/io/opentracing/util/GlobalTracerTest.java#L48_L57. I agree it's a little bit inconvenient.

**Comment by mabn** [comment]
I also went with reflection as I'd prefer not to spawn new JVM for each test case - it is especially expensive when starting Spring context - it can be reused for multiple tests if there's one JVM, but forking prevents that.

**Comment by sjoerdtalsma** [comment]
Maybe we could share the reflection utility code in a maven [`test-jar`](https://maven.apache.org/guides/mini/guide-attached-tests.html) for opentracing-util ?

That would save people from reinventing this hacky wheel, while not exposing unwanted behaviour in the main api.

**Comment by pavolloffay** [comment]
I think we should rather provide `reset` method directly on the `GlobalTracer`. It will make things much simpler, consumers should understand implications when calling it.

**Comment by sjoerdtalsma** [comment]
@pavolloffay Do you know of a use-case where this would be called in production code?

**Comment by pavolloffay** [comment]
Currently, I cannot think of any, but it seems something wrong with API design if we have to deal with reflection to make things work.

**Comment by sjoerdtalsma** [comment]
Not 'things': 'Abnormal' usecases which are only applicable to testing situations (and they shouldn't 'pollute' the api). We can always add a `reset` method later, but can never take it away again.

**Comment by yurishkuro** [comment]
+1 for test jar

**Comment by sjoerdtalsma** [comment]
@yurishkuro Thanks for merging!

**Comment by mabn** [comment]
The test jar solves it to some degree, but not entirely.

In case of spring boot services it's common to write tests which start spring application and hit it with some requests. If a service has more than 1 such test it will fail if run inside single JVM - when spring is starting second time. But running tests in separate JVMs is slow.

So in my case I prefer the initialization code to be re-runnable, even though it won't happen in production - it's just one less surprise for people not very familiar with opentracing. Otherwise almost everyone will google for the error message and maybe rediscover the test-jar.
So for now I just use reflection instead of test-jar - and it works ok.

I'm ok with closing this issue.

**Comment by yurishkuro** [comment]
I always like making exceptions more helpful to the users. If this is a common scenario in tests, we should probably extend the exception message to say "if you are getting this exception when running unit tests, see {url}" and link to the doc explaining how tests should be written.

**Comment by pavolloffay** [comment]
I don't think there is any exception or a specific error message which can be googled. Tests will be failing on incorrect finished spans count

**Comment by sjoerdtalsma** [comment]
@carlosalberto 
>What if we at least mention the error Yuri mentioned here (GlobalTracer.register() when there a tracer already registered)? Maybe it won't cover the case Pavol mentioned, but it's a good fix for now.

Not sure how this is still relevant after #269 is merged?
There the `register()` is replaced by `registerIfAbsent()` call which is clearer about the intended use _and_ won't throw this specific exception, rather return `false`.

**Comment by mabn** [comment]
From my point of view this issue can be closed now.

**Comment by pavolloffay** [comment]
@mabn @sjoerdtalsma thanks!

**Comment by carlosalberto** [comment]
@sjoerdtalsma Oh, definitely. Thanks!
