### ISSUE TITLE
Maven repository for opentracing-noop 0.30.0 has wrong content

### ISSUE THREAD

**Issue by Steve-Fontes** [opentracing/opentracing-java#171]
When you get the opentracing-noop jar file from [https://mvnrepository.com/artifact/io.opentracing/opentracing-noop/0.30.0](https://mvnrepository.com/artifact/io.opentracing/opentracing-noop/0.30.0) the contents still have the classes stored at io/opentracing rather than io/opentracing/noop, so when using io.opentracing:opentracing-noop:0.30.0 as a dependency for io.opentracing:opentracing-mock:0.30.0, you get errors.

**Comment by pavolloffay** [comment]
IIRC noop classes have been moved to a separate package after `0.30.0` release.

**Comment by Steve-Fontes** [comment]
But opentracing-mock 0.30.0 depends on opentracing-noop 0.30.0, and opentracing-mock expects the noop classes at io/opentracing/noop, but in the maven jar for noop 0.30.0, the noop classes are at io/opentracing, not at io/opentracing/noop

**Comment by pavolloffay** [comment]
I have decompiled http://central.maven.org/maven2/io/opentracing/opentracing-mock/0.30.0/opentracing-mock-0.30.0.jar and it's using  `io.opentracing.NoopActiveSpanSource`

**Comment by Steve-Fontes** [comment]
Sorry, I was trying to put the code into OSGI bundles, and the fact that mock and api are both in the io/opentracing directory made my code unable to find the mock classes. I'll find a work around. Thank you for taking the time to look at this.
