### ISSUE TITLE
MockTracer use TextMap propagator by default

### ISSUE THREAD

**Issue by pavolloffay** [opentracing/opentracing-java#177]
`MockTracer`, currently uses no/"printer" propagator by default. A better default is to use text map propagator.

**Comment by yurishkuro** [comment]
A conforming tracer is expected to support 3 standard propagation formats, textMap, http, and binary. I don't think there is such a thing as "default" propagator - there can be _default implementations_ for each of the format that decide on the specific encoding, like the naming of http headers. But given the conformance requirements I think those default implementations should be installed in the tracer by default, without explicit user configuration.

If that's what you're suggesting, then +1.

**Comment by pavolloffay** [comment]
PR https://github.com/opentracing/opentracing-java/pull/179
