### ISSUE TITLE
Tracer API uses non-idiomatic means to pass/specify timestamps

### ISSUE THREAD

**Issue by mcumings** [opentracing/opentracing-java#180]
Throughout the current API, timestamps are passed as native `long micros` values.

The idiomatic approach for specifying time values in Java changed in JDK 1.5 with the introduction of [TimeUnit](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/TimeUnit.html).  Once this class was introduced, APIs were encouraged to specify time durations as a `long duration, TimeUnit unit` tuple.  Examples within the JDK itself:
- [Future#get(long, TimeUnit)](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Future.html#get-long-java.util.concurrent.TimeUnit-)
- [CyclicBarrier#await(long, TimeUnit)](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CyclicBarrier.html#await-long-java.util.concurrent.TimeUnit-)
- [SynchronousQueue#offer(E, long, TimeUnit)](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/SynchronousQueue.html#offer-E-long-java.util.concurrent.TimeUnit-)
- etc...

Requiring direct provisioning in microseconds requires additional programmatic machinery to be provided by every API consumer irrespective of whether or not microsecond- level precision is required.  This is evidenced in the existing test code where microseconds are manufactured using `System.currentTimeMillis() * 1000`.  In real world code microsecond-level precision requires the creation of a custom clock which establishes a correlation between the value of `System.currentTimeMillis()` and `System.nanoTime()` at a relatively instant period of time, then using this data to manufacture microsecond timing through calculation of a delta in the nanosecond timer.

Provisioning timestamps using the `long, TimeUnit` tuple allows arbitrary precision to be supplied at the discretion of the consumer while retaining the tracer implementation's ability to consume a specific precision.

It sounds as if this issue has been discussed previously ad nauseam but the details of the original rationale may have been lost.  When discussing this in the `opentracing/public` Gitter channel, @bhs suggested I raise the visibility of this question to an Issue level and supply a PR to show the API surface area delta.

**Comment by yurishkuro** [comment]
+1 to switch to API with units.

**Comment by tylerbenson** [comment]
Nice work @mcumings. It touches a lot of places, but I think the result is much more idiomatic modern java. I also am 👍 for this change.

**Comment by bhs** [comment]
Thanks for the great writeup. I want to sleep on it, but my first reaction is positive for sure, esp given the context and conventions elsewhere in the JDK.

My main hesitation would normally be API breakage, but we already have bigger pending (breaking) changes. And much of this could be made backwards-compatible with overloading as we see fit.

**Comment by pavolloffay** [comment]
[`TimeUnit`](http://download.java.net/java/jdk9/docs/api/java/util/concurrent/TimeUnit.html) is used to model durations. All ^^ mentioned methods use time unit to specify units of given *timeout*. Whereas we have a slightly different use case. We capture only timestamps:

```java
span.finish(timestampMicros)
span.log(timestampMicros, logs)
```

It would definitely make sense if API had something like:

```java
span.finish(int duration, TimeUnit units)
```
e.g. force finishing spans with a specified duration.

**Comment by objectiser** [comment]
A timestamp is essentially a duration - it represents the number of a units since a reference point in time (e.g. 1st Jan 1970).

I don't think we want the application passing in a duration on finish as it would require the app to calculate it in reference to the start time - whereas it is easier for it to just provide its view of the current time at the point the `finish` method is called.

**Comment by mabn** [comment]
I don't recall seeing `TimeUnit` used for unix timestamps. The new API in Java 8 also does not use it, instead there are:
```
Instant.ofEpochMilli(long epochMilli)
Instant.ofEpochSecond(long epochSecond)
Instant.ofEpochSecond(long epochSecond, long nanoAdjustment)
Instant.now(Clock clock)
Instant.from(TemporalAccessor temporal)
```

**Comment by mcumings** [comment]
@mabn - That's an interesting idea.  I don't think it can be made to work in this case however.  In Spring's case the Java 8 class references were a part of the underlying implementation which used class presence to determine whether or not the Java 8 class could be used.  In our case we would need to expose the class as part of the API itself.

**Comment by tylerbenson** [comment]
If only folks would stop using old JVMs and just upgrade to Java 8 already.  :shakes_fist:

**Comment by mcumings** [comment]
Some of us are stuck with Android Dalvik/ART language levels. 😬

**Comment by pavolloffay** [comment]
I am more on -1 for this. I haven't seen using `TimeUnit` for timestamps in java APIs.

 If we want to simplify the timestamp related API, then provide alternative methods which accept `ms`.`System.currentTimeMillis()` is the most common way how to get a timestamp in Java.

**Comment by mcumings** [comment]
Raised https://github.com/opentracing/opentracing-java/pull/200 to target this change for v0.31.0 (and to remove some of the minor code cleanup stuff that was in the previous PR).

**Comment by tedsuo** [comment]
@pavolloffay @mcumings @tylerbenson bringing this issue up again as` v0.31` is coming to a close and I'd like to get this resolved in the current iteration if agreement can be reached.

**Comment by mcumings** [comment]
Is there an estimated timeframe for the Java 8 language level?  Given the contention maybe it's just best to wait.  Java 6 is ancient.  Java 7 is EOL unless you pay.  Maybe Java 8 isn't that far off...

**Comment by tedsuo** [comment]
Thanks Mike. Given that the current API is usable, and Java 8 provides a less contentious solution, I think we should hold off if it's all right with you.

Java 8 semantics come up often enough that a "Java 8+" API could be a considerable improvement. IMHO, we should wait for the current API to settle on a 1.0 before attempting that. But we could experiment with a new API via a Java 8 wrapper.

**Comment by mcumings** [comment]
Yeah, I think that's reasonable.  Better to make changes that are more obviously supported when the time is right than to force a less optimal solution.  If there's agreement to this approach from the other supporters of this issue then let's go ahead and close it out.

**Comment by yurishkuro** [comment]
just to clarify, so the proposal is to pass the timestamps as Instant and duration as TimeUnit? sgtm.

**Comment by tedsuo** [comment]
Thanks @mcumings.
