### ISSUE TITLE
inject & join coupling

### ISSUE THREAD

**Issue by toaler** [opentracing/opentracing-java#19]
I'm trying to understand why inject and join use the same carrier type.

For example, if the RPC is over HTTP, the carrier for inject can be any HTTP client HeaderGroup.

However the carrier for Join on the server side can be of a different type, say the Enumeration<String> headerNames in the case of pulling the headers from HttpServletRequest.

If the point of Tracer is to define a tracer per RPC technology (ie.  HttpTracer), would it make more sense to provide the capability to use two use different types if needed across join and inject?

Maybe I'm missing the point of the Tracer.

**Comment by michaelsembwever** [comment]
The same carrier type is not used between the inject and join methods.
It is expected and understood that the incoming wire is different to the outgoing wire.

The idea is that there exists one Tracer, and multiple Injector and Extractors implementations registered (configured) within it to handle the different wire types coming in and going out. See https://github.com/opentracing/opentracing-java/pull/11 for example.

**Comment by yurishkuro** [comment]
I am going to close this as I believe this is a non-issue, as @michaelsembwever explained. Feel free to reopen if there are still questions.
