### ISSUE TITLE
Should 'ignoreActiveSpan' be changed to 'ignoreScope'

### ISSUE THREAD

**Issue by objectiser** [opentracing/opentracing-java#222]
As mentioned here https://github.com/opentracing/opentracing-java/pull/219#discussion_r153752802 ?

Related to changes in 0.31.0 API discussed in #189

**Comment by pavolloffay** [comment]
I am fine with the `ignoreActiveSpan`, however It would be interesting to see what people  who don't know OT API think. 

For me the scope is like a "container" which can hold various objects. So when a span is being created you refer to the an active span and not scope.

The similar naming issues is with `SpanBuilder.startActive()`

What bothers me more is `SpanBuilder.startManual()` - I would rather remove/deprecate that and just keep the old `SpanBuilder.start()`. (Or rename to `startLocal`, manual implies that you have to do something manually which is not longer a case witouht refcounting and auto-finishing)

**Comment by tedsuo** [comment]
I agree on `start`, that seems obvious at this point.

With Scopes, we're always talking about the current value of the span contained in `ScopeManager.active()`. Should the names be `ignoreActive` and `startActive`? Just saying `ignoreScope` feels a little vague (which scope?).

`startActive` feels good to me. `ignoreActive` or `ignoreActiveScope` is fine by me... not of these feel "wrong."

**Comment by tedsuo** [comment]
This is also a bit of an aside, but related to this pattern. Do we want a `Span Tracer.activeSpan()` helper? `Tracer.scopeManager().active().span()` is a mouthful, and this will be a very, very common call in application code. Given that we have `startActive` and `ignoreActive`, the getter `activeSpan` feels like it closes the loop.

**Comment by carlosalberto** [comment]
Wondering if we should close this issue now, as the 0.31 API landed, and nobody has complained so far ;) @objectiser
