### ISSUE TITLE
please update maven central repository

### ISSUE THREAD

**Issue by dk900912** [opentracing/opentracing-java#224]
it does not contain ActiveSpan，git clone and mvn install to my local maven repository, then it works

**Comment by pavolloffay** [comment]
@dk900912 hi, what version do you mean? `0.30.0` has been published in maven central a long time ago.

**Comment by dk900912** [comment]
0.31.0-RC1! i removed these dependencies and update my maven project, but ActiveSpan still loss.

**Comment by objectiser** [comment]
@dk900912 Version 0.31.0 of the OpenTracing API will contain breaking changes - the main change being the way that active spans are managed. The ActiveSpan interface will no longer exist, and instead active spans will be managed via a Scope.

The 0.31.0-RC1 release was a release candidate to enable framework instrumentations and tracer implementations to try out the new changes. A second RC will be released soon.

**Comment by objectiser** [comment]
If interested in tracking this change, you can watch https://github.com/opentracing/opentracing-java/issues/189

There is also work on a compatibility layer that you may be interested in: https://github.com/opentracing/opentracing-java/pull/221

**Comment by dk900912** [comment]
@objectiser I got it, thank u so much

**Comment by carlosalberto** [comment]
Since 0.31 has already been published to Maven (http://repo1.maven.org/maven2/io/opentracing/opentracing-api/0.31.0/), as well as the v031 compatibility layer (http://repo1.maven.org/maven2/io/opentracing/opentracing-v030/0.0.4/), I'm going to close this issue. If I'm missing something, feel free to re-open it @dk900912 

Thanks!
