### ISSUE TITLE
Should we add `Tracer.activeSpan()`?

### ISSUE THREAD

**Issue by tedsuo** [opentracing/opentracing-java#227]
Do we want a `Tracer.activeSpan()` helper? `Tracer.scopeManager().active().span()` is a mouthful, and this will be a very, very common call in application code. Given that we have `startActive` and `ignoreActive` (or similar, see https://github.com/opentracing/opentracing-java/issues/222), the getter `activeSpan` feels like it closes the loop.

**Comment by carlosalberto** [comment]
Closing the issue as we merged a #228 as part of this.
