### ISSUE TITLE
StringTag.Set(Span, StringTag) bug

### ISSUE THREAD

**Issue by ndrwrbgs** [opentracing/opentracing-java#229]
Was this supposed to set the key to the key?
```
    public void set(Span span, StringTag tag) {
        span.setTag(super.key, tag.key);
    }
```

**Comment by ndrwrbgs** [comment]
@cwe1ss do you know who might be able to look at this?

**Comment by cwe1ss** [comment]
Hm... looks weird, yes.

/cc contributors with most commits: @bhs, @adriancole @pavolloffay, @michaelsembwever

**Comment by carlosalberto** [comment]
After a quick look, it does look correct...

But I'm not sure it's very helpful (not sure it's often required to use a Tag **key** as the Tag **value**, such as "component",  "error" or "span.kind", i.e `span.setTag("customTag", "span.kind");` ;) )

This change landed on June 2016, so it's kinda old. If it's really needed we should document it - else, probably deprecate it? @yurishkuro may know better ;)

**Comment by yurishkuro** [comment]
it looks weird - why does this method even exists? A signature for the string tag should be `set(Span, String)`

**Comment by yurishkuro** [comment]
i.e this: https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/tag/AbstractTag.java#L29

**Comment by yurishkuro** [comment]
It was added [here][1], I think it was a mistake. We should deprecate it.

[1]: https://github.com/opentracing/opentracing-java/pull/30/files#diff-1bb6bcf33ec7443304b5628e84245124

**Comment by carlosalberto** [comment]
`StringTag` already implements this one (`set(Span, String)`) so this method is a unneeded extra. Yes, lets deprecate it then 👍
