### ISSUE TITLE
Can we override traceId by custom uniqueId which we currenty have it across systems ?

### ISSUE THREAD

**Issue by hyginous29** [opentracing/opentracing-java#272]
Hi openTracing team,

Is there an option to override "traceId" by custom uniqueId ? 

This would help in using our existing uniqueId to build the trace across apps.

**Comment by yurishkuro** [comment]
It's not supported or recommended, although I'm sure people hacked around it.

Especially at the level of OpenTracing API we have no idea what format the underlying tracing system uses for trace ID (could be random 128bit, could be UUIDv4, could be hierarchical like MS does), or whether it supports externally provided IDs.

**Comment by yurishkuro** [comment]
Workaround: you can store the external ID as a tag on the span to correlate later.

**Comment by yurishkuro** [comment]
> If set my existing external ID as Tag, will it be propagated across the services/systems?

If you want that external ID propagated, you can save it to baggage instead of the tag.

> Also, can i see the whole trace using above external ID in the Trace UI ?

Depending on the tracing backend you may be able to search for spans with the tag with that external ID.

**Comment by hyginous29** [comment]
Thank you!

**Comment by KishoreKaushal** [comment]
@yurishkuro Since, its been one year, I would like to know the status of this issue. Is it officially supported, if not, then any future plans for this? Thank You.

**Comment by KishoreKaushal** [comment]
> 
> 
> > If set my existing external ID as Tag, will it be propagated across the services/systems?
> 
> If you want that external ID propagated, you can save it to baggage instead of the tag.
> 
> > Also, can i see the whole trace using above external ID in the Trace UI ?
> 
> Depending on the tracing backend you may be able to search for spans with the tag with that external ID.

I tried adding an item in Baggage:

`tracer.activeSpan().setTag("customId" , "12345");`

Unfortunately it was not propagated across other `spanContext` in the same trace.

**Comment by whiskeysierra** [comment]
> adding an item in Baggage
> setTag

:beetle: 

What you want is `setBaggageItem`.

**Comment by KishoreKaushal** [comment]
> 
> 
> > adding an item in Baggage
> > setTag
> 
> 🐞
> 
> What you want is `setBaggageItem`.

I am sorry I tried using the setBaggageItem. It's a typo.

**Comment by whiskeysierra** [comment]
Which implementation are you using?

**Comment by KishoreKaushal** [comment]
> 
> 
> Which implementation are you using?

I am using Jaeger and on top of that java-rabbitmq-client. 

I have three services say A, B, and C. A sends a message through a queue to B and then B forwards that message to C through another queue. I wanted a customId to propagated through the complete trace.

**Comment by whiskeysierra** [comment]
Not sure how jaeger uses rabbitmq to propagate baggage, but their docs suggest this:

> Limitation: since HTTP headers don’t preserve the case, Jaeger recommends baggage keys to be lowercase-snake-case, e.g. my-baggage-key-1.
>
> https://www.jaegertracing.io/docs/1.6/client-libraries/#baggage

**Comment by JamesFyyyah** [comment]
@KishoreKaushal I have exactly the same use case.
A workflow going through multiple Rabbit queues.
Did you find how to do it finally ?
