### ISSUE TITLE
Add registerIfAbsent(Tracer tracer) to GlobalTracer

### ISSUE THREAD

**Issue by pavolloffay** [opentracing/opentracing-java#286]
Related to #186 and https://github.com/opentracing/opentracing-java/pull/269#issuecomment-399699201

**Comment by SIMRAN1** [comment]
@pavolloffay @jpkrohling I want to work on this issue. May I proceed?

**Comment by jpkrohling** [comment]
My bad, I labeled it as suitable for Outreachy but didn't realize there was a PR already.

**Comment by sjoerdtalsma** [comment]
Can this be closed since #289 is already merged?

**Comment by carlosalberto** [comment]
Closing this one (#289 as mentioned ;) )
