### ISSUE TITLE
TCP Request Support in OpenTracing

### ISSUE THREAD

**Issue by TiMusBhardwaj** [opentracing/opentracing-java#292]
Hi,
I know open tracing works out of the box for HTTP request.
But, I am need to Trace my TCP server requests. As I have just started working with opentracing, I am still on my learning curve. 
Any help or suggestion is  welcome.

**Comment by tylerbenson** [comment]
One problem I see, is TCP doesn't really have a way of generically passing along metadata, thus it would be very challenging to propagate the trace relationship without also defining a protocol that would be required to be implemented on both sides.  If one side doesn't implement it, it might break.

Any suggestions on how to overcome this?

**Comment by jpkrohling** [comment]
@TiMusBhardwaj this is a great question, but it probably belongs somewhere else. I'm closing this one, but feel free to leave a comment with more details about your use case, so that we can direct you to the best place to discuss this.

**Comment by francisminu** [comment]
@TiMusBhardwaj  @tylerbenson  Any luck on getting this implemented?
