### ISSUE TITLE
Add close() method to io.opentracing.Tracer

### ISSUE THREAD

**Issue by SevaSafris** [opentracing/opentracing-java#302]
The Tracer interface does not define a close() method. Implementors of the Tracer interface, however, most often implement their own close() method to finalize traces, and to release resources. Since io.opentracing.Tracer.close() is not defined, application code that utilizes Tracer(s) must import the vendor-specific implementation in order for the close() method to be available. This effectively makes the application code coupled to the vendor, since the vendor-specific import is required.

By declaring a close() method in the io.opentracing.Tracer interface, vendor coupling can be avoided.

The close() method can be declared with a noop default, thus allowing for backward compatibility with all implementors of io.opentracing.Tracer that do not implement a close() method.

**Comment by jpkrohling** [comment]
> The close() method can be declared with a noop default

IIRC, this library is still on Java 6, so, no default implementation for interfaces are available :/

**Comment by SevaSafris** [comment]
I just checked the [io.opentracing:parent:pom](https://github.com/opentracing/opentracing-java/blob/master/pom.xml#L38), and it has compiler source and target set to 1.7.

**Comment by jpkrohling** [comment]
There seems to be an override here: https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/pom.xml#L32

**Comment by SevaSafris** [comment]
That override had eluded me. The override is itself a bad practice. So how should this move forward?
1) Declare the close() method without a default: This would force some vendors to have to implement the close() method if their Tracer(s) don't already have it implemented.
2) Remove the override: The class bytecode versions across the submodules are not consistent, which has the potential to lead to frustrating situations for vendors and app developers (this being one of them). I cannot comment on the reason for the override, as there is no comment in the pom where the override is set. Is this a path worth following? It's out of the scope of this issue, so a new issue would have to be created.
3) Do nothing: Keep the jdk1.6 override, and do not declare a Tracer.close(). This would force application code to be coupled to vendor implementations of the Tracer interface.

**Comment by SevaSafris** [comment]
Yes, this is an Option 4. However, this option is a hack that would further bury the primary issues (not having a close() on Tracer, and the jdk1.6 override). I beliebe Option 4 would be to incur a mindful technical debt.

**Comment by yurishkuro** [comment]
I am going to close this as a dup of #250, please continue discussion on close() there. Regarding dropping 1.6 - a separate issue altogether. We had a similar 1.6 discussion https://github.com/jaegertracing/jaeger-client-java/issues/511 and did not arrive at an agreement, and that's just a single implementation of the API.
