### ISSUE TITLE
trace-without-root-span

### ISSUE THREAD

**Issue by vbottu** [opentracing/opentracing-java#328]
I am trying to visualize the error trace in jaeger-ui by intentionally sending the wrong request, the span reported to ui has <trace-without-root-span> as heading, it could not say it is an error until unless i click on that to expand the trace.
![image](https://user-images.githubusercontent.com/19859827/51701231-9ed91500-1fd6-11e9-9150-2c9c866819b8.png)
 Do I need to configure anything in such scenarios? Attaching the screenshot. I am trying to emulate an error by hitting the endpoint that is not exposed which returns 404.

**Comment by black-adder** [comment]
Wrong repo, please open ticket here: https://github.com/jaegertracing/jaeger-ui/issues
