### ISSUE TITLE
Overriding timestamp on spans

### ISSUE THREAD

**Issue by devinbost** [opentracing/opentracing-java#366]
We're building a messaging system where we have messages containing timestamps that need to be reported to Jaeger via OpenTracing. 
Is there a way to override the timestamps on a Span so that the timestamps aren't hardcoded to when the spans are started or ended but instead can represent the timestamps expressed on the messages?

**Comment by whiskeysierra** [comment]
Would Jaeger even support that?

**Comment by yurishkuro** [comment]
https://github.com/opentracing/opentracing-java/blob/2df2a8983e35dff23c4fb894e5f5ae3f98f1cf7b/opentracing-api/src/main/java/io/opentracing/Tracer.java#L195-L196

https://github.com/opentracing/opentracing-java/blob/2df2a8983e35dff23c4fb894e5f5ae3f98f1cf7b/opentracing-api/src/main/java/io/opentracing/Span.java#L167

**Comment by devinbost** [comment]
@yurishkuro You rock. Thanks!
