### ISSUE TITLE
TextMapInjectAdapter does not implement TextMap

### ISSUE THREAD

**Issue by prathamshah9** [opentracing/opentracing-java#370]
TextMapInjectAdapter cannot be used in the `tracer.inject()` API as the current implementation of  TextMapInjectAdapter does not implement TextMap.
https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/propagation/TextMapInjectAdapter.java#L30
As seen in the implementation `TextMapInjectAdapter implements TextMapInject` but it does not implement `TextMap` in the hierarchy

**Comment by whiskeysierra** [comment]
Maybe this helps:

|                         | `extract(TEXT_MAP)` | `inject(TEXT_MAP)` | `extract(TEXT_MAP_EXTRACT)` | `inject(TEXT_MAP_INJECT)` |
|-------------------------|---------------------|--------------------|-----------------------------|---------------------------|
| `TextMapAdapter`        | ✔️                   | ✔️                  | ✔️                           | ✔️                         |
| `TextMapExtractAdapter` | ❌                   | ❌                  | ✔️                           | ❌                         |
| `TextMapInjectAdapter`  | ❌                   | ❌                  | ❌                           | ✔️                         |
