### ISSUE TITLE
Missing ScopeManager.active() method

### ISSUE THREAD

**Issue by rupinder10** [opentracing/opentracing-java#374]
I have java code that starts a span in one call and then later in time has to finish it. The code to finish it has the following structure:

span.finish(time);
tracer.scopeManager().active().close();

This code works fine with opentracing-api version 0.31 but the active() method has been removed from ScopeManager in version 0.33. 

This causes the spans to not show up properly.

**Comment by pavolloffay** [comment]
Yes, some methods have been first deprecated in 0.32.0 and removed in 0.33.0. These APIs were problematic and causing issues. 

In the new API it's expected that execution thread holds scope and closes it properly.


As this is not a bug I am it.
