### ISSUE TITLE
Make obvious that this is BYO(in-process propagation)

### ISSUE THREAD

**Issue by adriancole** [opentracing/opentracing-java#38]
in general, it might be nice to have a layer diagram of OT, since a lot of tracing systems (in java at least) do in-process propagation. That way it could be more easy to tell what's left to do.
ex I had a late ah-hah (or rather I forgot and learned again) when saw something thread-localling a span. @mansu also had questions about in-process propagation.

The [docs](http://opentracing.io/use-cases/#in-process-request-context-propagation) are actually quite specific, just it is not something you'd assume (in java).. possibly it could be just local to java (the assumption of implicit propagation), and moved to its README.

ex if you look at most java tracers, they highlight implicit propagation and how to achieve it, as that's needed to be understood before you get to a point of sending it out of process (inject/extract).

**Comment by adriancole** [comment]
https://github.com/opentracing/opentracing-java/pull/25 and  https://github.com/openzipkin/brave/pull/216 are examples of where there's confusion in implementation over this point.

**Comment by tedsuo** [comment]
Spring cleaning here: closing as this has been resolved with the new java API, which is now documented in the readme. If there are further issues related to documenting in-process propagation please reopen or make a new issue.
