### ISSUE TITLE
Clarify inject/extract exceptions

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-java#42]
The most common outcome of inject/extract methods that instrumentation needs to deal with are
1. success
2. unsupported format
3. empty carrier (extract only)
4. other exceptions (including invalid carrier type, corrupted carrier, etc.)

In Python API we specified exactly how tracer must react to these, specifically by throwing known exception for (2) and returning None for (3). The case (4) is usually a result of misconfiguration, so the exact exception is not that important.

I would like to have a well-defined (unchecked) exception type for (2), and specify that `null` must be returned for (3).

Side note: inject() documentation refers to carrier types instead of formats: `@param carrier the carrier for the SpanContext state. All Tracer.inject() implementations must support io.opentracing.propagation.TextMap and java.nio.ByteBuffer.`

@bensigelman @michaelsembwever

**Comment by bensigelman** [comment]
1, 2, and 3: Yes, let's do something like what we do in .py.

For 4, I know this came up before and I've thought about it some more. I do not like throwing exceptions on corrupt data. If I ran a service and didn't care about tracing or monitoring and some load-balancer or other machinery above me truncated a header for some reason, I definitely do not want to crash my process. Of course the service-owner "should" be catching exceptions, but IMO it would be better to return null when the carrier is corrupted... of course a Tracer impl could log an error or increment a "corrupted carrier" counter, so the failure doesn't have to be utterly silent.

**Comment by yurishkuro** [comment]
@bensigelman I agree with that sentiment. I think (4) can be subdivided into (4a) configuration/coding errors, such as passing invalid carrier type, and (4b) runtime conditions like corrupted trace. I wouldn't mind if tracer raised an exception for configuration/coding errors, making them easier to catch.

However, the distinction between (4a) and (4b) is not clear cut. E.g. say my format expects carrier as `Map<String, Object>` where some objects are Longs, others are Strings. If those types are not exact, that sounds more like a "corrupted carrier" (4b) than "wrong carrier type" (4a), even though the cause of it is not a runtime condition, but a configuration/coding error. 

Given the generics based API passing a wrong carrier type is less probable, which skews the whole (4) category towards (4b).

So should we say (4) should return null and NOT throw exception?

NB: of course there's a way to force the end user to catch exceptions by making them checked, but I'd rather not.

**Comment by bensigelman** [comment]
Yeah, +1 to all of the above. Forcing exception-catching is also acceptable in my mind, but it wouldn't be my preference.

**Comment by michaelsembwever** [comment]
`null` should never be returned. An empty or Noop SpanContext can be returned.

**Comment by yurishkuro** [comment]
I think null is more appropriate. If this was Scala, we would've defined the API as returning `Option[SpanContext]`, but since Java7 does not have such standard class, `null` is equivalent to `None`. On the other hand, empty or Noop SpanContext are not equivalent to None, they represent a new concept in the API.

**Comment by michaelsembwever** [comment]
> I think null is more appropriate.

I disagree. I've explained more in the PR.

> On the other hand, empty or Noop SpanContext are not equivalent to None, they represent a new concept in the API.

The Noop SpanContext exists already in the `NoopSpanBuilder`.
No new construct is introduced at the API level.

**Comment by yurishkuro** [comment]
`NoopSpanBuilder` is not part of the API, it's an implementation, which is only supposed to work with `NoopTracer`. We have never required that different Tracer implementations have to understand each other's Spans and Span Contexts. If you look at existing implementations of tracers, the first thing they do is cast Spans and Span Contexts to their own types. Therefore requiring tracers to return _their own version_ of no-op/empty span introduces a new concept.

**Comment by michaelsembwever** [comment]
> NoopSpanBuilder is not part of the API

Exactly. From the API perspective all you see is an empty SpanContext.

I'm sorry,  but returning `null` is just a really poor way of solving this, and definitely shouldn't be enforced at the API level.

**Comment by tedsuo** [comment]
Spring cleaning here: closing this issue as it is out of date, and many things have changed since the debate stopped. Feel free to reopen this issue or create a new one if you would like to continue.
