### ISSUE TITLE
Move Noop tracer to its own module opentracing-noop

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-java#45]
Noop tracer is currently in the `-impl` module, which has the following issues:
- `-impl` module was meant to contain an abstract skeleton for tracer implementations
- Noop tracer is never going to use that skeleton, so bundling it in the same jar increases the end user's dependencies

@bensigelman I know you prefer for it to be in `-api`, but (a) it's a harder sell, (b) taking a more pedantic view, in the world where everything is DI-ed and "sensible defaults" are considered an anti-pattern (e.g. an echo http server on netty requires 100+ lines of code), an instrumentation of a framework technically does not need the Noop tracer, only the API. So I think it's cleaner to have is as a separate artifact.

**Comment by michaelsembwever** [comment]
Can we come back to this at a later point? Seems like pre-mature optimisation, or just jumping the gun.

There no dependency tree introduced by anything here. 
In fact `-impl` has no dependencies what so ever already.
I can't see any immediate problem or debt.

**Comment by bhs** [comment]
@yurishkuro this is done, right? Closing...
