### ISSUE TITLE
Rename `-impl` and `-impl-java8` modules to better reflect what they are

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-java#46]
These modules are meant to be abstract skeletons for tracer implementations. Calling them "impl" is misleading to the people visiting the repo.

**Comment by michaelsembwever** [comment]
I'm open to suggestions. But this has precedence in the java world, `*-api.jar` are supported with `*-impl.jar` siblings without indicating a complete implementation or bridge. The concept here is building half the API in `-impl` of that that is defined in the SPI `-api`.

I can understand that this is confusion, but it is common enough in java.

**Comment by bhs** [comment]
Obsolete post-#121.
