### ISSUE TITLE
Start maintaining CHANGELOG.md

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-java#54]
https://github.com/opentracing/opentracing-java/pull/51#issuecomment-246407394

**Comment by tedsuo** [comment]
We should do this as part of going v1.0.0, seems like a convenient moment.

**Comment by carlosalberto** [comment]
Shall we close this after adding a `CHANGELOG` file after releasing 0.31? Or shall we keep this issue around for some time as a reminder? @yurishkuro @tedsuo

**Comment by yurishkuro** [comment]
I think we need to update RELEASE.md to add a step that before doing a release the changelog should be updated.

**Comment by MikeGoldsmith** [comment]
@yurishkuro are you happy for this to be closed regarding #268?

**Comment by yurishkuro** [comment]
+1. Closing.
