### ISSUE TITLE
Outdated contributing guidelines

### ISSUE THREAD

**Issue by mabn** [opentracing/opentracing-java#62]
[CONTRIBUTING.md](https://github.com/opentracing/opentracing-java/blob/master/CONTRIBUTING.md) advises to apply Square Code Style which indents with 2 spaces, but the code in opentracing-java is indented with 4 spaces - it seems that this code style is not in active use.

**Comment by michaelsembwever** [comment]
Fixed. Thanks for spotting this @mabn .
