### ISSUE TITLE
AbstractSpanBuilder.childOf should not return NoopSpanBuilder

### ISSUE THREAD

**Issue by mabn** [opentracing/opentracing-java#64]
This is in a direct contradiction to the changes done in https://github.com/opentracing/opentracing-java/pull/56 ("A child of a NoopSpan is a NoopSpan"), but I believe that the behaviour introduced there is not correct.

It seems that there are two uses for Noop implementation:
1. The default empty tracer implementation
2. NoopSpanContext might be returned from `Tracer.extract` when there is no span context in the carrier (instead of null) - to indicate "a lack of"

#56 uses the 2nd meaning of NoopSpanContext and the reasoning is that it makes the fluent builder usable when there is no parent SpanContext - does not require conditional checking for presence:
```
SpanContext parent = tracer.extract(Format.Builtin.TEXT_MAP, adapter);
try (Span span = tracer.buildSpan("some-name").asChildOf(parent).start()) {
    // server processes request
    return response;
}
```

The problem is that the behaviour ("A child of a NoopSpan is a NoopSpan") it's not what I expect. **I expect that a child of a "no span" (or NoopSpan, or null) is just a span without a parent**. And not a NoopSpan, but a Span implementation used by the current tracer.
Why? Because the child span is going to be lost - NoopSpan does not record tags, has empty `finish()` implementation and the tracer will not be aware of it.

I'm not sure why there is a requirement in [brave-opentracing](https://github.com/openzipkin/brave-opentracing/pull/5/files#diff-6c41a867ac46d2b874b3e7ee714271a3R345) for it to behave this way.

I'd suggest to:
- always return `this` inside AbstractSpanBuilder. Something like this:
  ```
    @Override
    public final AbstractSpanBuilder asChildOf(SpanContext parent) {
        if(!(parent instanceof NoopSpanContext)) {
            this.addReference(References.CHILD_OF, parent);
        }
        return this;
    }
  ```
- add a null check if nulls are not the way to go
- clearly state what represents an empty span context - in the api (javadoc for `Tracer.extract`).

Though it might be better to add `SpanContext.isEmpty` method to the API, make it explicit and get rid of this weird "instanceof".

**Comment by michaelsembwever** [comment]
> I expect that a child of a "no span" (or NoopSpan, or null) is just a span without a parent. 

This is the false premise (to the direction taken so far).
An empty context provides a noop span, and the child of a noop span is implicitly another noop span.
An explicit action is required to go from an empty context to an empty (rather than noop) span.
This is what provides the most fluent api for users. 


> Though it might be better to add SpanContext.isEmpty method to the API, make it explicit and get rid of this weird "instanceof".

I suspect this has a lot of merit. The current situation does lead to having to understand a number of complexities in the design and use patterns.

**Comment by mabn** [comment]
I do not follow...
When a request is received I want a span to start which will be tracked/reported no matter if the request(carrier) contains span context or not. In both these cases I'd like following code to work properly:
```
SpanContext parent = tracer.extract(Format.Builtin.TEXT_MAP, adapter);
Span span = tracer.buildSpan("some-name").asChildOf(parent).start())
```
But if empty context provides a noop span, then I'll need some conditional like:
```
SpanContext parent = tracer.extract(Format.Builtin.TEXT_MAP, adapter);
SpanBuilder builder = tracer.buildSpan("some-name");
Span span;
if(parent is empty-context) {
   span = builder.build(); // can't use asChildOf because it will create NoopSpan and I don't want it
} else {
  span = builder.asChildOf(parent).build();
}
```
Do I understand this correctly?

**Comment by michaelsembwever** [comment]
> This is in a direct contradiction to the changes done in #56 ("A child of a NoopSpan is a NoopSpan"), but I believe that the behaviour introduced there is not correct.

FTR i think it'll be more constructive focusing on discussions that happened in https://github.com/opentracing/opentracing-java/pull/58


> But if empty context provides a noop span, then I'll need some conditional like…

That is correct.
The premise is that in any decent sized microservices platform the majority of services do not force sampling/tracing, that they only continue tracing requests that are already being traced. This would also be the default approach when adding tracing to libraries and frameworks. For more info see https://github.com/opentracing/opentracing-java/pull/58#discussion_r81646716

**Comment by bensigelman** [comment]
@michaelsembwever as has been demonstrated in other OT language implementations, there is no need for this sort of conditional *as long as* `asChildOf` (and `followsFrom`) are documented to accept the empty/null/whatever `SpanContext`... I feel rather strongly that we should allow the user to just write

```java
span = builder.asChildOf(parentContext).build();
```

regardless of whether parentContext is an `EmptyContext` or `null` or whatever we've agreed is most appropriate in modern Java.

**Comment by michaelsembwever** [comment]
> `span = builder.asChildOf(parentContext).build();`

They can. The discussion here is to whether tracing off an empty context here is implicitly forced or not. My argument in https://github.com/opentracing/opentracing-java/pull/58#discussion_r81646716 is that you can easily save yourself hundreds or thousands of lines of code by not implicitly forcing tracing.

Both side of the argument though clarify the need for a better mechanism, like `spanContext.isEmpty()` to exist.

**Comment by mabn** [comment]
@michaelsembwever I've read #58 discussion - it makes sense for it to behave like you described.

But if it's a part of some instrumented framework you'll still need some extra code to decide if this the instrumented service is the service which starts traces or not.

It would be ideal if the same construction (`builder.asChildOf(parentContext).build()`) could be used in both cases and the behaviour explicitly configurable (via sampling policy?).

**Comment by michaelsembwever** [comment]
> It would be ideal if the same construction (builder.asChildOf(parentContext).build()) could be used in both cases and the behaviour explicitly configurable (via sampling policy?)

Agreed. And it's been previously discussed and agreed upon :-)

**Comment by tedsuo** [comment]
Spring cleaning here: closing this issue as it is out of date. Feel free to reopen or create a new issue if you'd like to continue.
