### ISSUE TITLE
Duration of a Span

### ISSUE THREAD

**Issue by gkumar7** [opentracing/opentracing-java#69]
I have been following open tracing for quite a while now and am excited about what is being done!

In this issue, I would like to discuss about the duration of a Span. In [AbstractSpanBuilder](https://github.com/opentracing/opentracing-java/blob/ef2f50b60aeacda509abdb21156d2af2535a94d1/opentracing-impl/src/main/java/io/opentracing/impl/AbstractSpanBuilder.java#L31), start is initialized, but this value is not used.

Tests utilizing this class, such as [TestSpanBuilder](https://github.com/opentracing/opentracing-java/blob/ef2f50b60aeacda509abdb21156d2af2535a94d1/opentracing-impl/src/test/java/io/opentracing/impl/TestSpanBuilder.java#L28) define start to be when the Span is created. 

Should the duration of a Span start at the creation of the Span object or the SpanBuilder object? I assumed the former based on the tests, but the initialization in AbstractSpanBuilder seems a bit misleading.

**Comment by bensigelman** [comment]
The clock starts for the Span once `start()` is called on the builder, UNLESS an explicit timestamp was provided (in which case that timestamp will always take precedence). If that's not what the AbstractSpanBuilder does, that's a bug.

FWIW, I would like to see the `-impl` code moved into github.com/opentracing-contrib somehow, though it's not my first priority and keeps on getting pushed back. There is no requirement to use any of the `-impl` machinery if it's not actually helping, though.
