### ISSUE TITLE
MockTracer custom recorders

### ISSUE THREAD

**Issue by pavolloffay** [opentracing/opentracing-java#74]
Hello,

I would like to contribute a custom recorder for `MockTracer`. In the most cases recording spans to the list is sufficient, however, it would be good to be able to send spans to an arbitrary recorder (e.g. console for demo purposes).

```
interface Recorder {
    void record(Span span);
}

....
public MockTracer() {
 this(Propagator.PRINTER, Recorder.LIST)
}

public MockTracer(Propagator propagator, Recorder recorder) {
}
```

@adriancole @bensigelman @yurishkuro what do you think?

**Comment by bensigelman** [comment]
@pavolloffay I don't have any great objections... I can imagine creating something a little more powerful/flexible like https://github.com/opentracing/basictracer-go for Java and building off of that, too.

My only minor concern is that you're describing something other than a true "mock" tracer... so the name is drifting a bit. But I can live with that.

**Comment by yurishkuro** [comment]
One concern I have is that currently finished spans are accessible via the MockTracer itself. If you introduce a Recorder concept, that becomes weird (leak in encapsulation).

Maybe a simpler solution is just to add `onSpanFinished(MockSpan span)` no-op method and override it where needed?

**Comment by pavolloffay** [comment]
@yurishkuro `onSpanFinished(MockSpan span)` would work for me.

Thanks

**Comment by pavolloffay** [comment]
Closing as https://github.com/opentracing/opentracing-java/issues/76 is merged.
