### ISSUE TITLE
out of date I think

### ISSUE THREAD

**Issue by adriancole** [opentracing/opentracing-java#81]
I think many are calling OpenTracing version 1 or something and it is here 0.20.7 including methods marked deprecated. If these methods are in fact no longer in the api, they should be removed instead of leading people on. If the api is version 1, then it should probably be marked so..

sound sensible?

**Comment by wu-sheng** [comment]
Maybe we should release OpenTracing-java 1.0, remove all `@deprecated` APIs, and only follow the Spec 1.0

**Comment by bensigelman** [comment]
The OpenTracing spec itself is at v1.0; OT-Java is at whatever version it's at. :)

I am still grumpy that it has all of these impl helper classes (AbstractSpan, etc) in the core repo... they do not need to be there and tend to confuse people. And getting rid of the deprecated bits also makes plenty of sense.

**Comment by wu-sheng** [comment]
The whole `opentracing-impl` thing is not part of Official OpenTracing-Java. :P 

For me, these `AbstractSpan` classes (in `opentracing-impl` module, including `NoopSpan`)  like demonstrations or  reference implementations. Because OT does not require them.

@adriancole thoughts?

**Comment by sjoerdtalsma** [comment]
@bhs
> I am still grumpy that it has all of these impl helper classes (AbstractSpan, etc) in the core repo...

:+1: Plus that you can't actually use them unless you move yourself into the `io.opentracing.impl` package (which may become overcrowded real soon for this exact reason!)

**Comment by tedsuo** [comment]
Spring cleaning (for issues) here: closing this issue as it is out of date. There is a milestone for v1.0.0 release of java, which can be found here: https://github.com/opentracing/opentracing-java/milestone/1

Feel free to create a new issue discussing what should be in the v1.0.0 milestone if you are interested.
