### ISSUE TITLE
Why does LogData have no getters?

### ISSUE THREAD

**Issue by aquinton** [opentracing/opentracing-java#83]
Sorry if this has been discussed before but what is the intended purpose of AbstractSpan.getLogs()? It returns a list of objects which have no getters - so no code can access this data - making that method somewhat useless.

**Comment by aquinton** [comment]
I guess I can just make a pull request to add getters for immutable copies and see if that elicits some response?

**Comment by bensigelman** [comment]
@aquinton sorry, missed this.

As discussed on #44, there's reason to remove the `-impl` package from this repo entirely. As you are observing, it is not fully-thought-out and, as far as I know, the production implementations of the `-api` artifact don't even use it. (I could be wrong about that last bit)

That said, if you want to add those getters, fine with me. Def isn't very useful in its current state.

**Comment by tedsuo** [comment]
Spring cleaning here: closing this issue as debate has ceased and the API has changed. If there is still interest, please reopen or create a new issue.
